# Пример конфигурации для .streamlit/secrets.toml
# Скопируйте этот файл в .streamlit/secrets.toml и настройте под ваши нужды

# Настройки аутентификации
[auth]
# URL для перенаправления после аутентификации
# Для локальной разработки:
redirect_uri = "http://localhost:8501/oauth2callback"
# Для продакшена замените на ваш домен:
# redirect_uri = "https://your-app.streamlit.app/oauth2callback"

# Секретный ключ для подписи cookies (сгенерируйте случайную строку)
cookie_secret = "your-super-secret-cookie-key-change-this"

# Конфигурация Google OAuth
[auth.google]
client_id = "your-google-client-id.apps.googleusercontent.com"
client_secret = "your-google-client-secret"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"

# Альтернативно, можно использовать Microsoft
# [auth.microsoft]
# client_id = "your-microsoft-client-id"
# client_secret = "your-microsoft-client-secret"
# server_metadata_url = "https://login.microsoftonline.com/{tenant}/v2.0/.well-known/openid-configuration"

# Настройки приложения
GEMINI_API_KEY = "your-gemini-api-key"
AUTH_ENABLED = true
AUTH_PASSWORD = "admin123"  # Не используется с OIDC, но оставлено для совместимости
